### ISSUE TITLE
EasyButton failures - ubuntu.sh - cpan deps for Mouse and ZMQ::FFI

### ISSUE THREAD

**Issue by cjhc** [csirtgadgets/massive-octo-spice#466]
Both require --force to install due to failed tests with current code and repos:
cpanm Mouse@2.4.1
cpanm ZMQ::FFI@0.17

**Comment by wesyoung** [comment]
are you trying to run easy button with the latest release? or off master?

**Comment by cjhc** [comment]
@wesyoung I've tried both, but started with the guide here: [https://github.com/csirtgadgets/massive-octo-spice/wiki/PlatformUbuntu](url)

```
$ curl -Ls https://raw.githubusercontent.com/csirtgadgets/massive-octo-spice/master/hacking/platforms/easybutton_curl.sh | sudo bash -
$ sudo chown `whoami`:`whoami` ~/.cif.yml
```

**Comment by cjhc** [comment]
Running another test today using the EasyButton. The cpanm Mouse failed, parsing through the log.

> Semicolon seems to be missing at t/040_type_constraints/005_util_type_coercion.t line 27.
> syntax error at t/040_type_constraints/005_util_type_coercion.t line 28, near "coerce "
> Execution of t/040_type_constraints/005_util_type_coercion.t aborted due to compilation errors.
> # Looks like your test exited with 255 just after 1.
> t/040_type_constraints/005_util_type_coercion.t ................
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 7/8 subtests


> Test Summary Report
> -------------------
> t/020_attributes/014_misc_attribute_coerce_lazy.t            (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> t/040_type_constraints/005_util_type_coercion.t              (Wstat: 65280 Tests: 1 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 8 tests but ran 1.
> t/040_type_constraints/018_custom_parameterized_types.t      (Wstat: 0 Tests: 28 Failed: 0)
>   TODO passed:   13, 19-20, 22
> Files=293, Tests=6085, 18 wallclock secs ( 1.10 usr  0.44 sys + 14.37 cusr  1.42 csys = 17.33 CPU)
> Result: FAIL
> Failed 2/293 test programs. 0/6085 subtests failed.
> -> FAIL Installing Mouse failed. See /home/cif/.cpanm/work/1482518826.3351/build.log for details. Retry with --force to force install it.
> 21 distributions installed

Running an install test of Mouse without specifying version:
`cif@massive-octo-spice:~$ sudo cpanm --wget --mirror https://cpan.metacpan.org --skip-installed Mouse`

> Test Summary Report
> -------------------
> t/020_attributes/014_misc_attribute_coerce_lazy.t            (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> t/040_type_constraints/005_util_type_coercion.t              (Wstat: 65280 Tests: 1 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 8 tests but ran 1.
> t/040_type_constraints/018_custom_parameterized_types.t      (Wstat: 0 Tests: 28 Failed: 0)
>   TODO passed:   13, 19-20, 22
> Files=296, Tests=6105, 23 wallclock secs ( 1.49 usr  0.52 sys + 18.85 cusr  2.44 csys = 23.30 CPU)
> Result: FAIL
> Failed 2/296 test programs. 0/6105 subtests failed.
> -> FAIL Installing Mouse failed. See /home/cif/.cpanm/work/1482520095.11210/build.log for details. Retry with --force to force install it.
> 1 distribution installed

**Comment by cjhc** [comment]
Discovered that Ubuntu libmouse-perl (http://packages.ubuntu.com/trusty/libmouse-perl) was installed. Removal prior to EasyButton run results in completion, however cif -p fails:

> cif@massive-octo-spice:~$ cif -p
> Data input to inflate is not in libz format at /usr/local/share/perl/5.18.2/CIF/SDK/Client.pm line 189.

See https://github.com/csirtgadgets/massive-octo-spice/issues/468

**Comment by wesyoung** [comment]
i think this is fixed in 2.00.06- tested against ubuntu 14.05.5

let me know and we'll open new bugs if they come up..

**Comment by cjhc** [comment]
@wesyoung still failing using the EasyButton via curl on Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64):

> Building and testing Mouse-2.4.1 ... FAIL
> ! Installing Mouse failed. See /home/cif/.cpanm/work/1483565582.14562/build.log for details. Retry with --force to force install it.
> 21 distributions installed

Also failed in massive-octo-spice-2.00.06:

> Building and testing Mouse-2.4.1 ... FAIL
> ! Installing Mouse failed. See /home/cif/.cpanm/work/1483566649.14574/build.log for details. Retry with --force to force install it.
> 21 distributions installed

From the log:

> Test Summary Report
> -------------------
> t/020_attributes/014_misc_attribute_coerce_lazy.t            (Wstat: 65280 Te
> sts: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> t/040_type_constraints/005_util_type_coercion.t              (Wstat: 65280 Te
> sts: 1 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 8 tests but ran 1.
> t/040_type_constraints/018_custom_parameterized_types.t      (Wstat: 0 Tests:
>  28 Failed: 0)
>   TODO passed:   13, 19-20, 22
> Files=293, Tests=6085, 18 wallclock secs ( 1.29 usr  0.38 sys + 14.64 cusr  1
> .57 csys = 17.88 CPU)
> Result: FAIL
> Failed 2/293 test programs. 0/6085 subtests failed.

Confirmed "cpanm --force Mouse@2.4.1" is in ubuntu.sh.

Added "--notest" to ubuntu.sh, and re-ran easybutton_curl.sh. The build completed successfully.

Post-script, running into the issues with libz format:

> cif@cif:~/massive-octo-spice-2.00.06$ sudo chown `whoami`:`whoami` ~/.cif.ymlcif@cif:~/massive-octo-spice-2.00.06$ cif -p
> Data input to inflate is not in libz format at /usr/local/share/perl/5.18.2/CIF/SDK/Client.pm line 189.
> cif@cif:~/massive-octo-spice-2.00.06$ 

Manually did cpan install for cif-sdk:

> cif@cif:~/massive-octo-spice-2.00.06$ sudo cpanm https://github.com/csirtgadgets/p5-cif-sdk/archive/2.00.tar.gz
> --> Working on https://github.com/csirtgadgets/p5-cif-sdk/archive/2.00.tar.gz
> Fetching https://github.com/csirtgadgets/p5-cif-sdk/archive/2.00.tar.gz ... OK
> Configuring p5-cif-sdk-2.00 ... OK
> Building and testing CIF-SDK-2.00 ... OK
> Successfully installed CIF-SDK-2.00
> 1 distribution installed
> cif@cif:~/massive-octo-spice-2.00.06$ cif -p
> roundtrip: 0.546744 ms
> roundtrip: 0.542425 ms
> roundtrip: 0.935369 ms
> roundtrip: 0.602078 ms

Confirmed this line is in ubuntu.sh: "cpanm https://github.com/csirtgadgets/p5-cif-sdk/archive/2.00.tar.gz"

Taking a snapshot, and re-building to test with changes above.

**Comment by cjhc** [comment]
Build via easybutton still fails Mouse install until run a second time.

Manual cpanm install for p5-cif-sdk is still required, see #468

**Comment by cjhc** [comment]
... running easybutton from within the untarred release results in a git clone without the local changed... duh. Missed that.

suggestion @wesyoung @giovino - easybutton_release.sh or _local.sh or something that doesn't git pull the repo.

**Comment by wesyoung** [comment]
aye; yea we made a lot of mistakes in v2 when it came to deployment (ansible hadn't gained much traction yet...). v3 is quite a bit easier for this reason, put a lot of emphasis on deployment .. and much more to come (gonna split out some of the deployment stuff to a sep repo).

*probably* easy button should be "docker run"; which we try to keep up with in v3:

https://github.com/csirtgadgets/cif-docker

(need to add more readme stuff, etc... but you get the idea).
